#!/bin/sh
# Run by github/github codespaces after starting

# Install some developer tools and setup Linux how I like it
apt-get install -y \
  exa grc ripgrep shellcheck zsh-autosuggestions \
  locate

# Setup the database for locate
updatedb
